#!/usr/bin/env python3
"""Generate Swift source for the VSOP87D Earth series.

Input : VSOP87D.ear (original Bureau des Longitudes distribution format)
Output: SajuKit/Sources/SajuKit/Astro/Generated/VSOP87Earth.swift

Each retained term contributes  A * cos(B + C * tau)  where tau is Julian
millennia from J2000.0 (TT). Series are truncated by amplitude; the sum of
dropped amplitudes per series is reported and embedded in the header so the
truncation error budget is auditable.

Usage: python3 scripts/gen_vsop87.py <path-to-VSOP87D.ear>
"""

import sys
from pathlib import Path

# Amplitude thresholds per variable. L/B in radians, R in AU.
# Budget: total dropped amplitude in L must stay under ~2.5e-8 rad (0.005"),
# which is negligible against the 24s-per-arcsecond scale of solar terms.
THRESHOLDS = {"L": 1e-9, "B": 2e-9, "R": 5e-9}
VAR_NAMES = {1: "L", 2: "B", 3: "R"}


def parse(path):
    series = {}  # (var, power) -> [(A, B, C)]
    var = power = None
    for line in Path(path).read_text().splitlines():
        if "VSOP87 VERSION" in line:
            assert "EARTH" in line, "expected the Earth file"
            var = VAR_NAMES[int(line.split("VARIABLE")[1].split()[0])]
            power = int(line.split("*T**")[1].split()[0])
            series[(var, power)] = []
            continue
        parts = line.split()
        if len(parts) < 3 or var is None:
            continue
        a, b, c = (float(x) for x in parts[-3:])
        series[(var, power)].append((a, b, c))
    return series


def emit(series, out_path, src_name):
    stats, chunks = [], []
    for (var, power) in sorted(series):
        terms = series[(var, power)]
        thr = THRESHOLDS[var]
        kept = [t for t in terms if t[0] >= thr]
        dropped_sum = sum(t[0] for t in terms if t[0] < thr)
        stats.append(
            f"//   {var}{power}: kept {len(kept)}/{len(terms)} terms, "
            f"dropped amplitude sum {dropped_sum:.3e}"
        )
        rows = "\n".join(
            f"        {a!r}, {b!r}, {c!r}," for a, b, c in kept
        )
        chunks.append(
            f"    static let {var.lower()}{power}: [Double] = [\n{rows}\n    ]\n"
        )

    lists = {
        v: ", ".join(
            f"{v.lower()}{p}" for (vv, p) in sorted(series) if vv == v
        )
        for v in ("L", "B", "R")
    }
    body = "\n".join(chunks)
    stats_block = "\n".join(stats)
    out_path.write_text(f"""\
// Generated by scripts/gen_vsop87.py — DO NOT EDIT BY HAND.
//
// VSOP87D heliocentric Earth series (ecliptic and equinox of date).
// Source: {src_name} — P. Bretagnon & G. Francou,
// "Planetary theories in rectangular and spherical variables", A&A 202 (1988).
//
// Truncation report (amplitudes in rad for L/B, AU for R):
{stats_block}
//
// Evaluation: value = Σ_p τ^p · Σ_i A·cos(B + C·τ), τ = Julian millennia from J2000 (TT).

enum VSOP87Earth {{
{body}
    static let lSeries: [[Double]] = [{lists['L']}]
    static let bSeries: [[Double]] = [{lists['B']}]
    static let rSeries: [[Double]] = [{lists['R']}]
}}
""")
    total = sum(
        len([t for t in ts if t[0] >= THRESHOLDS[v]])
        for (v, _), ts in series.items()
    )
    print(f"wrote {out_path} — {total} terms retained")
    for s in stats:
        print(s.removeprefix("//   "))


if __name__ == "__main__":
    src = Path(sys.argv[1])
    out = Path(__file__).resolve().parent.parent / (
        "SajuKit/Sources/SajuKit/Astro/Generated/VSOP87Earth.swift"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    emit(parse(src), out, src.name)
